// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAITujPdyI_TEqFIlye2vOyG7gqZS9sc',
    appId: '1:750574663042:web:ed9420d9336f5db1638b9b',
    messagingSenderId: '750574663042',
    projectId: 'studyonline-uasmp04',
    authDomain: 'studyonline-uasmp04.firebaseapp.com',
    storageBucket: 'studyonline-uasmp04.appspot.com',
    measurementId: 'G-205XCZSSDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDQ5A35Yoiw6YqhPInjJpdKKMQKxRRL8',
    appId: '1:750574663042:android:55ae30bccc100e68638b9b',
    messagingSenderId: '750574663042',
    projectId: 'studyonline-uasmp04',
    storageBucket: 'studyonline-uasmp04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSS0KUGlOrDJ-pL00UkkeEMgGFhyr1wq8',
    appId: '1:750574663042:ios:9d73ffe6c5678950638b9b',
    messagingSenderId: '750574663042',
    projectId: 'studyonline-uasmp04',
    storageBucket: 'studyonline-uasmp04.appspot.com',
    androidClientId: '750574663042-b4n09496gv7oe145s7cm6ruuu3l4p9g5.apps.googleusercontent.com',
    iosClientId: '750574663042-8jr9sgbpgli244c1s8jge2glhuam5i3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSS0KUGlOrDJ-pL00UkkeEMgGFhyr1wq8',
    appId: '1:750574663042:ios:9d73ffe6c5678950638b9b',
    messagingSenderId: '750574663042',
    projectId: 'studyonline-uasmp04',
    storageBucket: 'studyonline-uasmp04.appspot.com',
    androidClientId: '750574663042-b4n09496gv7oe145s7cm6ruuu3l4p9g5.apps.googleusercontent.com',
    iosClientId: '750574663042-8jr9sgbpgli244c1s8jge2glhuam5i3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasApp',
  );
}
